FROM java:8

ENV GRADLE_HOME /opt/gradle
ENV GRADLE_VERSION 4.10.2

# installing gradle
RUN wget --no-verbose --output-document=gradle.zip "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" && \
    unzip gradle.zip && \
    rm gradle.zip && \
    mv "gradle-${GRADLE_VERSION}" "${GRADLE_HOME}/" && \
    ln --symbolic "${GRADLE_HOME}/bin/gradle" /usr/bin/gradle && \
    groupadd --system --gid 1000 gradle && \
    useradd --system --gid gradle --uid 1000 --shell /bin/bash --create-home gradle && \
    mkdir /home/gradle/.gradle && \
    chown --recursive gradle:gradle /home/gradle && \
    ln -s /home/gradle/.gradle /root/.gradle

# todo: load marytts using the web installer

ENV PATH="${PATH}:/marytts/target/marytts-builder-5.3-SNAPSHOT/bin"
