FROM maven:3-jdk-8

# preparing marytts
RUN git clone https://github.com/marytts/marytts.git && \
    cd /marytts && \
    git checkout 5.x

# installing marytts
RUN cd /marytts && \
    mvn install

ENV PATH="${PATH}:/marytts/target/marytts-builder-5.3-SNAPSHOT/bin"
